version: '2'
services:
  api-service:
    container_name: api-service-container
    build:
      context: api-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    image: api-service:latest
    networks:
      - container-practice-network
    environment:
      EMPLOYEE_SERVICE_URL: http://employee-service:8082
  employee-service:
      container_name: employee-service-container
      build:
        context: employee-service
        dockerfile: Dockerfile
      image: employee-service:latest
      networks:
        - container-practice-network
      environment:
        DB_HOST: "employee-service-db"
      depends_on:
        employee-service-db:
          condition: service_healthy
  employee-service-db:
    container_name: mysql-server-container
    image: mysql:8.0
    networks:
      - container-practice-network
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_USER: "miztli"
      MYSQL_PASSWORD: "4321"
      MYSQL_DATABASE: "employees-db"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD || exit 1
      start_period: 5s
      interval: 7s
      timeout: 5s
      retries: 2
networks:
  container-practice-network:
    driver: bridge