scrape_configs:
  - job_name: 'APIServiceJob'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'http://api-service:8080' ]
        labels:
          application: 'API Service'
  - job_name: 'EmployeeServiceJob'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'http://employee-service:8082' ]
        labels:
          application: 'Employee Service'